export const constants = {
    
    GET_PIZZAS_REQUEST: 'GET_PIZZAS_REQUEST',
    GET_PIZZAS_SUCCESS: 'GET_PIZZAS_SUCCESS',
    GET_PIZZAS_FAILED: 'GET_PIZZAS_FAILED',

    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

    PLACE_ORDER_REQUEST: 'PLACE_ORDER_REQUEST',
    PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
    PLACE_ORDER_FAILED: 'PLACE_ORDER_FAILED',

    GET_USER_ORDERS_REQUEST: 'GET_USER_ORDERS_REQUEST',
    GET_USER_ORDERS_SUCCESS: 'GET_USER_ORDERS_SUCCESS',
    GET_USER_ORDERS_FAILED: 'GET_USER_ORDERS_FAILED',

    ADD_PIZZA_REQUEST: 'ADD_PIZZA_REQUEST',
    ADD_PIZZA_SUCCESS: 'ADD_PIZZA_SUCCESS',
    ADD_PIZZA_FAILED: 'ADD_PIZZA_FAILED',

    GET_PIZZABYID_REQUEST: 'GET_PIZZABYID_REQUEST',
    GET_PIZZABYID_SUCCESS: 'GET_PIZZABYID_SUCCESS',
    GET_PIZZABYID_FAILED: 'GET_PIZZABYID_FAILED',

    EDIT_PIZZA_REQUEST: 'EDIT_PIZZA_REQUEST',
    EDIT_PIZZA_SUCCESS: 'EDIT_PIZZA_SUCCESS',
    EDIT_PIZZA_FAILED: 'EDIT_PIZZA_FAILED',

    GET_ALL_ORDERS_REQUEST: 'GET_ALL_ORDERS_REQUEST',
    GET_ALL_ORDERS_SUCCESS: 'GET_ALL_ORDERS_SUCCESS',
    GET_ALL_ORDERS_FAILED: 'GET_ALL_ORDERS_FAILED',

    GET_ALL_USER_REQUEST: 'GET_ALL_USER_REQUEST',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILED: 'GET_ALL_USER_FAILED',

}